"""mengubah kolom gpt ke nullable

Revision ID: be1910f7fde7
Revises: 6a8f12795229
Create Date: 2024-02-15 11:19:48.118969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be1910f7fde7'
down_revision = '6a8f12795229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.alter_column('gpt_solution',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.alter_column('gpt_solution',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###
