"""Menambah task html

Revision ID: c57a5c9b24ed
Revises: 10c4c75d036f
Create Date: 2024-03-19 14:06:07.430249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c57a5c9b24ed'
down_revision = '10c4c75d036f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_html', sa.String(length=10000000), nullable=False))
        batch_op.alter_column('quest',
               existing_type=mysql.LONGTEXT(),
               type_=sa.String(length=10000000),
               existing_nullable=False)
        batch_op.alter_column('objektifitas',
               existing_type=mysql.LONGTEXT(),
               type_=sa.String(length=10000000),
               existing_nullable=False)
        batch_op.alter_column('answer',
               existing_type=mysql.LONGTEXT(),
               type_=sa.String(length=10000000),
               existing_nullable=False)
        batch_op.alter_column('kode_quest',
               existing_type=mysql.LONGTEXT(),
               type_=sa.String(length=10000000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.alter_column('kode_quest',
               existing_type=sa.String(length=10000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
        batch_op.alter_column('answer',
               existing_type=sa.String(length=10000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
        batch_op.alter_column('objektifitas',
               existing_type=sa.String(length=10000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
        batch_op.alter_column('quest',
               existing_type=sa.String(length=10000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
        batch_op.drop_column('task_html')

    # ### end Alembic commands ###
